// Package udevrules models the Linux fix from Story 3. Because Linux names USB
// serial adapters by plug order (/dev/ttyUSB0, ttyUSB1, ...), software that
// hardcodes a path cannot reliably find a device. The fix maps each device's
// burned-in serial number to a permanent symlink via a udev rule, for example:
//
//	SUBSYSTEM=="tty", ATTRS{serial}=="AH01T3XC", SYMLINK+="physio_monitor"
//
// This package extracts serials from `udevadm info -a` output and generates a
// deterministic, validated rules file from a serial -> name mapping.
package udevrules

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// serialLine matches an attribute line such as:
//
//	ATTRS{serial}=="AH01T3XC"
//
// as printed by `udevadm info -a /dev/ttyUSB0`.
var serialLine = regexp.MustCompile(`ATTRS\{serial\}=="([^"]+)"`)

// namePattern restricts symlink names to safe device-node characters.
var namePattern = regexp.MustCompile(`^[A-Za-z0-9_]+$`)

// ExtractSerials returns every serial found in udevadm-style text, in order of
// appearance with duplicates removed. Real `udevadm info -a` output walks the
// device tree and may print the same serial on several parent stanzas, so
// dedup keeps the first occurrence.
func ExtractSerials(udevadm string) []string {
	var out []string
	seen := make(map[string]bool)
	for _, m := range serialLine.FindAllStringSubmatch(udevadm, -1) {
		s := m[1]
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

// Mapping pairs a device serial with the stable symlink name it should get.
type Mapping struct {
	Serial string
	Name   string
}

// Generate builds a udev rules file from the given mappings. Output is sorted
// by symlink name so the file is deterministic regardless of input order. It
// rejects empty fields, invalid names, and duplicate serials or names.
func Generate(mappings []Mapping) (string, error) {
	bySerial := make(map[string]string)
	byName := make(map[string]string)
	for _, m := range mappings {
		serial := strings.TrimSpace(m.Serial)
		name := strings.TrimSpace(m.Name)
		if serial == "" {
			return "", fmt.Errorf("udevrules: empty serial for name %q", name)
		}
		if name == "" {
			return "", fmt.Errorf("udevrules: empty name for serial %q", serial)
		}
		if !namePattern.MatchString(name) {
			return "", fmt.Errorf("udevrules: invalid symlink name %q (use only letters, digits, underscore)", name)
		}
		if prev, ok := bySerial[serial]; ok {
			return "", fmt.Errorf("udevrules: duplicate serial %q maps to both %q and %q", serial, prev, name)
		}
		if prev, ok := byName[name]; ok {
			return "", fmt.Errorf("udevrules: duplicate name %q maps to both %q and %q", name, prev, serial)
		}
		bySerial[serial] = name
		byName[name] = serial
	}

	names := make([]string, 0, len(byName))
	for name := range byName {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# Generated by bench-reliability: stable names for lab serial devices.\n")
	b.WriteString("# Each rule maps a burned-in serial number to a permanent /dev symlink.\n")
	for _, name := range names {
		fmt.Fprintf(&b, "SUBSYSTEM==\"tty\", ATTRS{serial}==%q, SYMLINK+=%q\n", byName[name], name)
	}
	return b.String(), nil
}
